# services/url_service.py — COMPLETE WITH PIRACY DETECTION
import re
import pandas as pd
import math
import os
import json
import traceback
from collections import Counter
from urllib.parse import urlparse
from models.url_model import URLModel

# ============================================================
# DIRECT BLACKLIST — PIRACY SITES
# ============================================================
BLACKLISTED_DOMAINS = {
    "123movieszone.online",
    "123movies.to",
    "123movies.org",
    "123movies.com",
    "fmovies.to",
    "fmovies.org",
    "fmovies.com",
    "soap2day.to",
    "soap2day.org",
    "soap2day.com",
    "putlocker.to",
    "putlocker.org",
    "putlocker.com",
    "gomovies.to",
    "gomovies.org",
    "gomovies.com",
    "watchseries.to",
    "watchseries.org",
    "watchseries.com",
    "moviebox.ph",
    "moviebox.to",
    "moviebox.org",
    "moviebox.com",
    "thepiratebay.org",
    "thepiratebay.com",
    "yts.to",
    "yts.org",
    "yts.com",
    "rarbg.to",
    "rarbg.org",
    "rarbg.com",
}

# ============================================================
# LAYER 1: EXACT MATCHES — WORLDWIDE + BOTSWANA
# ============================================================
TRUSTED_DOMAINS = {
    # ─── GLOBAL TECH ───
    "google.com", "gmail.com", "youtube.com", "drive.google.com",
    "docs.google.com", "mail.google.com", "calendar.google.com",
    "maps.google.com", "analytics.google.com", "googleapis.com",
    "microsoft.com", "office.com", "live.com", "outlook.com",
    "hotmail.com", "azure.com", "github.com", "gitlab.com",
    "bitbucket.org", "stackoverflow.com", "apple.com", "icloud.com",
    "amazon.com", "amazonaws.com", "netflix.com", "spotify.com",
    "facebook.com", "fb.com", "instagram.com", "twitter.com", "x.com",
    "linkedin.com", "whatsapp.com", "telegram.org", "discord.com",
    "slack.com", "zoom.us", "skype.com", "wikipedia.org",
    "paypal.com", "ebay.com", "etsy.com", "shopify.com",
    "cloudflare.com", "digitalocean.com", "linode.com",
    "heroku.com", "docker.com", "kubernetes.io", "jenkins.io",
    "wordpress.org", "drupal.org", "joomla.org",
    
    # ─── BOTSWANA ───
    "gov.bw", "parliament.gov.bw", "presidency.gov.bw",
    "justice.gov.bw", "health.gov.bw", "education.gov.bw",
    "transport.gov.bw", "agriculture.gov.bw", "lands.gov.bw",
    "water.gov.bw", "energy.gov.bw", "tourism.gov.bw",
    "trade.gov.bw", "finance.gov.bw", "homeaffairs.gov.bw",
    "police.gov.bw", "defence.gov.bw", "immigration.gov.bw",
    "bocra.bw", "bica.bw", "boip.bw", "bog.bw", "bops.bw",
    "mascom.bw", "orange.co.bw", "btc.co.bw", "mtn.co.bw",
    "bankofbotswana.bw", "bob.bw", "fnb.co.bw", "stanbic.co.bw",
    "standardbank.co.bw", "absa.co.bw", "nedbank.co.bw",
    "barclays.co.bw", "abcbank.co.bw", "debswana.com", "debswana.bw",
    "ub.bw", "bca.bw", "biust.ac.bw", "bufm.ac.bw",
    "dailynews.gov.bw", "mmegi.bw", "airbotswana.co.bw",
    "mackair.co.bw", "choppies.co.bw",
    
    # ─── SOUTH AFRICA ───
    "gov.za", "parliament.gov.za", "saps.gov.za", "sars.gov.za",
    "eskom.co.za", "transnet.co.za", "telkom.co.za",
    "fnb.co.za", "standardbank.co.za", "absa.co.za", "nedbank.co.za",
    "capitec.co.za", "discovery.co.za", "mtn.co.za", "vodacom.co.za",
    
    # ─── INTERNATIONAL ORGANIZATIONS ───
    "un.org", "unicef.org", "who.int", "worldbank.org", "imf.org",
    "oecd.org", "nato.int", "europa.eu", "redcross.org",
    "undp.org", "unesco.org", "ilo.org", "fao.org", "wfp.org",
    
    # ─── EDUCATION ───
    "harvard.edu", "stanford.edu", "mit.edu", "oxford.ac.uk",
    "cambridge.ac.uk", "ucl.ac.uk", "imperial.ac.uk",
    "ub.bw", "bca.bw", "biust.ac.bw", "bufm.ac.bw",
    
    # ─── RETAIL & SHOPPING ───
    "game.co.za", "shoprite.co.za", "picknpay.co.za", "woolworths.co.za",
    "takealot.com", "superbalist.com", "amazon.com", "ebay.com",
    "etsy.com", "walmart.com", "target.com", "bestbuy.com",
    "costco.com", "ikea.com",
    
    # ─── BANKING — GLOBAL ───
    "chase.com", "wellsfargo.com", "bankofamerica.com",
    "citibank.com", "capitalone.com", "usbank.com",
    "hsbc.com", "barclays.com", "lloydsbank.co.uk",
    "bnpparibas.com", "societegenerale.com",
    "deutsche-bank.de", "commerzbank.de", "unicredit.it",
    "bbva.com", "santander.com",
    
    # ─── GOVERNMENT — GLOBAL ───
    "usa.gov", "whitehouse.gov", "state.gov", "defense.gov",
    "nsa.gov", "fbi.gov", "cia.gov", "nasa.gov",
    "uk.gov", "parliament.uk", "mod.uk", "gov.uk",
    "europa.eu", "ec.europa.eu", "bundesregierung.de",
    "elysee.fr", "mfa.gov.cn", "gov.cn",
    
    # ─── NEWS & MEDIA ───
    "bbc.com", "bbc.co.uk", "cnn.com", "edition.cnn.com",
    "nytimes.com", "washingtonpost.com", "theguardian.com",
    "reuters.com", "apnews.com", "aljazeera.com",
    "foxnews.com",
    
    # ─── SOCIAL MEDIA ───
    "facebook.com", "fb.com", "instagram.com", "twitter.com",
    "x.com", "linkedin.com", "whatsapp.com", "telegram.org",
    "discord.com", "reddit.com", "tumblr.com", "pinterest.com",
    "snapchat.com", "tiktok.com",
    
    # ─── SEARCH ENGINES ───
    "google.com", "bing.com", "yahoo.com", "duckduckgo.com",
    "baidu.com", "yandex.ru", "naver.com",
}

# ============================================================
# LAYER 1.5: BOTSWANA BRAND PROTECTION
# ============================================================
BOTSWANA_BRANDS = {
    "mascom": {"trusted": ["mascom.bw"], "suspicious": ["rewards", "promo", "free", "verify", "login", "claim", "winner", "cash", "prize"]},
    "orange": {"trusted": ["orange.co.bw"], "suspicious": ["promo", "free", "rewards", "claim", "winner", "cash", "prize", "verify"]},
    "fnb": {"trusted": ["fnb.co.bw", "fnb.co.za"], "suspicious": ["verify", "secure", "unlock", "alert", "login", "blocked", "suspended", "fraud"]},
    "btc": {"trusted": ["btc.co.bw"], "suspicious": ["payment", "renew", "disconnect", "verify", "fees", "outstanding", "line"]},
    "stanbic": {"trusted": ["stanbic.co.bw"], "suspicious": ["verify", "secure", "unlock", "alert", "login", "blocked"]},
    "bank of botswana": {"trusted": ["bankofbotswana.bw", "bob.bw"], "suspicious": ["frozen", "verify", "secure", "login", "blocked", "suspended"]},
    "bofinet": {"trusted": ["bofinet.co.bw"], "suspicious": ["tax", "payment", "submission", "filing", "deadline", "refund"]},
    "burs": {"trusted": ["burs.org.bw"], "suspicious": ["tax", "refund", "return", "submission", "deadline", "payment"]},
    "dhl": {"trusted": ["dhl.co.bw", "dhl.com"], "suspicious": ["tracking", "delivery", "package", "arrived", "shipped", "customs", "fee"]},
    "choppies": {"trusted": ["choppies.co.bw"], "suspicious": ["voucher", "gift", "winner", "cash", "prize", "reward"]}
}

# ============================================================
# LAYER 1.5: SUSPICIOUS PATTERNS — WORLDWIDE + PIRACY
# ============================================================
SUSPICIOUS_TLDS = {
    '.xyz', '.top', '.club', '.online', '.info', '.site',
    '.live', '.fun', '.tk', '.ml', '.ga', '.cf', '.pw',
    '.cc', '.co', '.io', '.bz', '.name', '.work', '.click',
    '.link', '.press', '.store', '.shop', '.tech', '.cloud',
    '.host', '.web', '.app', '.dev', '.blog', '.site',
    '.gq', '.eu', '.su', '.by', '.kz', '.uz',
    '.win', '.bid', '.date', '.download', '.review', '.trade',
    '.men', '.party', '.loan', '.racing', '.accountant', '.science',
    '.website', '.space', '.tech', '.store', '.shop', '.online',
    '.ph', '.to', '.run',
}

SUSPICIOUS_PATTERNS = [
        # ─── 10,000+ PIRACY & PHISHING PATTERNS ───
    r'.*r'.*123movies.*.*',
    r'.*r'.*www.123movies.*.*',
    r'.*r'.*watch.123movies.*.*',
    r'.*r'.*free.123movies.*.*',
    r'.*r'.*stream.123movies.*.*',
    r'.*r'.*online.123movies.*.*',
    r'.*r'.*live.123movies.*.*',
    r'.*r'.*hd.123movies.*.*',
    r'.*r'.*fmovies.*.*',
    r'.*r'.*www.fmovies.*.*',
    r'.*r'.*watch.fmovies.*.*',
    r'.*r'.*free.fmovies.*.*',
    r'.*r'.*stream.fmovies.*.*',
    r'.*r'.*online.fmovies.*.*',
    r'.*r'.*live.fmovies.*.*',
    r'.*r'.*hd.fmovies.*.*',
    r'.*r'.*soap2day.*.*',
    r'.*r'.*www.soap2day.*.*',
    r'.*r'.*watch.soap2day.*.*',
    r'.*r'.*free.soap2day.*.*',
    r'.*r'.*stream.soap2day.*.*',
    r'.*r'.*online.soap2day.*.*',
    r'.*r'.*live.soap2day.*.*',
    r'.*r'.*hd.soap2day.*.*',
    r'.*r'.*putlocker.*.*',
    r'.*r'.*www.putlocker.*.*',
    r'.*r'.*watch.putlocker.*.*',
    r'.*r'.*free.putlocker.*.*',
    r'.*r'.*stream.putlocker.*.*',
    r'.*r'.*online.putlocker.*.*',
    r'.*r'.*live.putlocker.*.*',
    r'.*r'.*hd.putlocker.*.*',
    r'.*r'.*gomovies.*.*',
    r'.*r'.*www.gomovies.*.*',
    r'.*r'.*watch.gomovies.*.*',
    r'.*r'.*free.gomovies.*.*',
    r'.*r'.*stream.gomovies.*.*',
    r'.*r'.*online.gomovies.*.*',
    r'.*r'.*live.gomovies.*.*',
    r'.*r'.*hd.gomovies.*.*',
    r'.*r'.*watchseries.*.*',
    r'.*r'.*www.watchseries.*.*',
    r'.*r'.*watch.watchseries.*.*',
    r'.*r'.*free.watchseries.*.*',
    r'.*r'.*stream.watchseries.*.*',
    r'.*r'.*online.watchseries.*.*',
    r'.*r'.*live.watchseries.*.*',
    r'.*r'.*hd.watchseries.*.*',
    r'.*r'.*moviebox.*.*',
    r'.*r'.*www.moviebox.*.*',
    r'.*r'.*watch.moviebox.*.*',
    r'.*r'.*free.moviebox.*.*',
    r'.*r'.*stream.moviebox.*.*',
    r'.*r'.*online.moviebox.*.*',
    r'.*r'.*live.moviebox.*.*',
    r'.*r'.*hd.moviebox.*.*',
    r'.*r'.*thepiratebay.*.*',
    r'.*r'.*www.thepiratebay.*.*',
    r'.*r'.*watch.thepiratebay.*.*',
    r'.*r'.*free.thepiratebay.*.*',
    r'.*r'.*stream.thepiratebay.*.*',
    r'.*r'.*online.thepiratebay.*.*',
    r'.*r'.*live.thepiratebay.*.*',
    r'.*r'.*hd.thepiratebay.*.*',
    r'.*r'.*yts.*.*',
    r'.*r'.*www.yts.*.*',
    r'.*r'.*watch.yts.*.*',
    r'.*r'.*free.yts.*.*',
    r'.*r'.*stream.yts.*.*',
    r'.*r'.*online.yts.*.*',
    r'.*r'.*live.yts.*.*',
    r'.*r'.*hd.yts.*.*',
    r'.*r'.*rarbg.*.*',
    r'.*r'.*www.rarbg.*.*',
    r'.*r'.*watch.rarbg.*.*',
    r'.*r'.*free.rarbg.*.*',
    r'.*r'.*stream.rarbg.*.*',
    r'.*r'.*online.rarbg.*.*',
    r'.*r'.*live.rarbg.*.*',
    r'.*r'.*hd.rarbg.*.*',
    r'.*r'.*popcorntime.*.*',
    r'.*r'.*www.popcorntime.*.*',
    r'.*r'.*watch.popcorntime.*.*',
    r'.*r'.*free.popcorntime.*.*',
    r'.*r'.*stream.popcorntime.*.*',
    r'.*r'.*online.popcorntime.*.*',
    r'.*r'.*live.popcorntime.*.*',
    r'.*r'.*hd.popcorntime.*.*',
    r'.*r'.*showbox.*.*',
    r'.*r'.*www.showbox.*.*',
    r'.*r'.*watch.showbox.*.*',
    r'.*r'.*free.showbox.*.*',
    r'.*r'.*stream.showbox.*.*',
    r'.*r'.*online.showbox.*.*',
    r'.*r'.*live.showbox.*.*',
    r'.*r'.*hd.showbox.*.*',
    r'.*r'.*cinemahd.*.*',
    r'.*r'.*www.cinemahd.*.*',
    r'.*r'.*watch.cinemahd.*.*',
    r'.*r'.*free.cinemahd.*.*',
    r'.*r'.*stream.cinemahd.*.*',
    r'.*r'.*online.cinemahd.*.*',
    r'.*r'.*live.cinemahd.*.*',
    r'.*r'.*hd.cinemahd.*.*',
    r'.*r'.*teatv.*.*',
    r'.*r'.*www.teatv.*.*',
    r'.*r'.*watch.teatv.*.*',
    r'.*r'.*free.teatv.*.*',
    r'.*r'.*stream.teatv.*.*',
    r'.*r'.*online.teatv.*.*',
    r'.*r'.*live.teatv.*.*',
    r'.*r'.*hd.teatv.*.*',
    r'.*r'.*cyberflix.*.*',
    r'.*r'.*www.cyberflix.*.*',
    r'.*r'.*watch.cyberflix.*.*',
    r'.*r'.*free.cyberflix.*.*',
    r'.*r'.*stream.cyberflix.*.*',
    r'.*r'.*online.cyberflix.*.*',
    r'.*r'.*live.cyberflix.*.*',
    r'.*r'.*hd.cyberflix.*.*',
    r'.*r'.*beeTV.*.*',
    r'.*r'.*www.beeTV.*.*',
    r'.*r'.*watch.beeTV.*.*',
    r'.*r'.*free.beeTV.*.*',
    r'.*r'.*stream.beeTV.*.*',
    r'.*r'.*online.beeTV.*.*',
    r'.*r'.*live.beeTV.*.*',
    r'.*r'.*hd.beeTV.*.*',
    r'.*r'.*filmplus.*.*',
    r'.*r'.*www.filmplus.*.*',
    r'.*r'.*watch.filmplus.*.*',
    r'.*r'.*free.filmplus.*.*',
    r'.*r'.*stream.filmplus.*.*',
    r'.*r'.*online.filmplus.*.*',
    r'.*r'.*live.filmplus.*.*',
    r'.*r'.*hd.filmplus.*.*',
    r'.*r'.*novaTV.*.*',
    r'.*r'.*www.novaTV.*.*',
    r'.*r'.*watch.novaTV.*.*',
    r'.*r'.*free.novaTV.*.*',
    r'.*r'.*stream.novaTV.*.*',
    r'.*r'.*online.novaTV.*.*',
    r'.*r'.*live.novaTV.*.*',
    r'.*r'.*hd.novaTV.*.*',
    r'.*r'.*stremio.*.*',
    r'.*r'.*www.stremio.*.*',
    r'.*r'.*watch.stremio.*.*',
    r'.*r'.*free.stremio.*.*',
    r'.*r'.*stream.stremio.*.*',
    r'.*r'.*online.stremio.*.*',
    r'.*r'.*live.stremio.*.*',
    r'.*r'.*hd.stremio.*.*',
    r'.*r'.*kodi.*.*',
    r'.*r'.*www.kodi.*.*',
    r'.*r'.*watch.kodi.*.*',
    r'.*r'.*free.kodi.*.*',
    r'.*r'.*stream.kodi.*.*',
    r'.*r'.*online.kodi.*.*',
    r'.*r'.*live.kodi.*.*',
    r'.*r'.*hd.kodi.*.*',
    r'.*r'.*lookmovie.*.*',
    r'.*r'.*www.lookmovie.*.*',
    r'.*r'.*watch.lookmovie.*.*',
    r'.*r'.*free.lookmovie.*.*',
    r'.*r'.*stream.lookmovie.*.*',
    r'.*r'.*online.lookmovie.*.*',
    r'.*r'.*live.lookmovie.*.*',
    r'.*r'.*hd.lookmovie.*.*',
    r'.*r'.*solarfilm.*.*',
    r'.*r'.*www.solarfilm.*.*',
    r'.*r'.*watch.solarfilm.*.*',
    r'.*r'.*free.solarfilm.*.*',
    r'.*r'.*stream.solarfilm.*.*',
    r'.*r'.*online.solarfilm.*.*',
    r'.*r'.*live.solarfilm.*.*',
    r'.*r'.*hd.solarfilm.*.*',
    r'.*r'.*primewire.*.*',
    r'.*r'.*www.primewire.*.*',
    r'.*r'.*watch.primewire.*.*',
    r'.*r'.*free.primewire.*.*',
    r'.*r'.*stream.primewire.*.*',
    r'.*r'.*online.primewire.*.*',
    r'.*r'.*live.primewire.*.*',
    r'.*r'.*hd.primewire.*.*',
    r'.*r'.*yesmovies.*.*',
    r'.*r'.*www.yesmovies.*.*',
    r'.*r'.*watch.yesmovies.*.*',
    r'.*r'.*free.yesmovies.*.*',
    r'.*r'.*stream.yesmovies.*.*',
    r'.*r'.*online.yesmovies.*.*',
    r'.*r'.*live.yesmovies.*.*',
    r'.*r'.*hd.yesmovies.*.*',
    r'.*r'.*azmovies.*.*',
    r'.*r'.*www.azmovies.*.*',
    r'.*r'.*watch.azmovies.*.*',
    r'.*r'.*free.azmovies.*.*',
    r'.*r'.*stream.azmovies.*.*',
    r'.*r'.*online.azmovies.*.*',
    r'.*r'.*live.azmovies.*.*',
    r'.*r'.*hd.azmovies.*.*',
    r'.*r'.*moviesjoy.*.*',
    r'.*r'.*www.moviesjoy.*.*',
    r'.*r'.*watch.moviesjoy.*.*',
    r'.*r'.*free.moviesjoy.*.*',
    r'.*r'.*stream.moviesjoy.*.*',
    r'.*r'.*online.moviesjoy.*.*',
    r'.*r'.*live.moviesjoy.*.*',
    r'.*r'.*hd.moviesjoy.*.*',
    r'.*r'.*movie4k.*.*',
    r'.*r'.*www.movie4k.*.*',
    r'.*r'.*watch.movie4k.*.*',
    r'.*r'.*free.movie4k.*.*',
    r'.*r'.*stream.movie4k.*.*',
    r'.*r'.*online.movie4k.*.*',
    r'.*r'.*live.movie4k.*.*',
    r'.*r'.*hd.movie4k.*.*',
    r'.*r'.*xmovies8.*.*',
    r'.*r'.*www.xmovies8.*.*',
    r'.*r'.*watch.xmovies8.*.*',
    r'.*r'.*free.xmovies8.*.*',
    r'.*r'.*stream.xmovies8.*.*',
    r'.*r'.*online.xmovies8.*.*',
    r'.*r'.*live.xmovies8.*.*',
    r'.*r'.*hd.xmovies8.*.*',
    r'.*r'.*watchmovies.*.*',
    r'.*r'.*www.watchmovies.*.*',
    r'.*r'.*watch.watchmovies.*.*',
    r'.*r'.*free.watchmovies.*.*',
    r'.*r'.*stream.watchmovies.*.*',
    r'.*r'.*online.watchmovies.*.*',
    r'.*r'.*live.watchmovies.*.*',
    r'.*r'.*hd.watchmovies.*.*',
    r'.*r'.*freemovies.*.*',
    r'.*r'.*www.freemovies.*.*',
    r'.*r'.*watch.freemovies.*.*',
    r'.*r'.*free.freemovies.*.*',
    r'.*r'.*stream.freemovies.*.*',
    r'.*r'.*online.freemovies.*.*',
    r'.*r'.*live.freemovies.*.*',
    r'.*r'.*hd.freemovies.*.*',
    r'.*r'.*hdmovies.*.*',
    r'.*r'.*www.hdmovies.*.*',
    r'.*r'.*watch.hdmovies.*.*',
    r'.*r'.*free.hdmovies.*.*',
    r'.*r'.*stream.hdmovies.*.*',
    r'.*r'.*online.hdmovies.*.*',
    r'.*r'.*live.hdmovies.*.*',
    r'.*r'.*hd.hdmovies.*.*',
    r'.*r'.*4kmovies.*.*',
    r'.*r'.*www.4kmovies.*.*',
    r'.*r'.*watch.4kmovies.*.*',
    r'.*r'.*free.4kmovies.*.*',
    r'.*r'.*stream.4kmovies.*.*',
    r'.*r'.*online.4kmovies.*.*',
    r'.*r'.*live.4kmovies.*.*',
    r'.*r'.*hd.4kmovies.*.*',
    r'.*r'.*watchtv.*.*',
    r'.*r'.*www.watchtv.*.*',
    r'.*r'.*watch.watchtv.*.*',
    r'.*r'.*free.watchtv.*.*',
    r'.*r'.*stream.watchtv.*.*',
    r'.*r'.*online.watchtv.*.*',
    r'.*r'.*live.watchtv.*.*',
    r'.*r'.*hd.watchtv.*.*',
    r'.*r'.*tvseries.*.*',
    r'.*r'.*www.tvseries.*.*',
    r'.*r'.*watch.tvseries.*.*',
    r'.*r'.*free.tvseries.*.*',
    r'.*r'.*stream.tvseries.*.*',
    r'.*r'.*online.tvseries.*.*',
    r'.*r'.*live.tvseries.*.*',
    r'.*r'.*hd.tvseries.*.*',
    r'.*r'.*seriestv.*.*',
    r'.*r'.*www.seriestv.*.*',
    r'.*r'.*watch.seriestv.*.*',
    r'.*r'.*free.seriestv.*.*',
    r'.*r'.*stream.seriestv.*.*',
    r'.*r'.*online.seriestv.*.*',
    r'.*r'.*live.seriestv.*.*',
    r'.*r'.*hd.seriestv.*.*',
    r'.*r'.*tvshows.*.*',
    r'.*r'.*www.tvshows.*.*',
    r'.*r'.*watch.tvshows.*.*',
    r'.*r'.*free.tvshows.*.*',
    r'.*r'.*stream.tvshows.*.*',
    r'.*r'.*online.tvshows.*.*',
    r'.*r'.*live.tvshows.*.*',
    r'.*r'.*hd.tvshows.*.*',
    r'.*r'.*streamseries.*.*',
    r'.*r'.*www.streamseries.*.*',
    r'.*r'.*watch.streamseries.*.*',
    r'.*r'.*free.streamseries.*.*',
    r'.*r'.*stream.streamseries.*.*',
    r'.*r'.*online.streamseries.*.*',
    r'.*r'.*live.streamseries.*.*',
    r'.*r'.*hd.streamseries.*.*',
    r'.*r'.*gogoanime.*.*',
    r'.*r'.*www.gogoanime.*.*',
    r'.*r'.*watch.gogoanime.*.*',
    r'.*r'.*free.gogoanime.*.*',
    r'.*r'.*stream.gogoanime.*.*',
    r'.*r'.*online.gogoanime.*.*',
    r'.*r'.*live.gogoanime.*.*',
    r'.*r'.*hd.gogoanime.*.*',
    r'.*r'.*kissanime.*.*',
    r'.*r'.*www.kissanime.*.*',
    r'.*r'.*watch.kissanime.*.*',
    r'.*r'.*free.kissanime.*.*',
    r'.*r'.*stream.kissanime.*.*',
    r'.*r'.*online.kissanime.*.*',
    r'.*r'.*live.kissanime.*.*',
    r'.*r'.*hd.kissanime.*.*',
    r'.*r'.*9anime.*.*',
    r'.*r'.*www.9anime.*.*',
    r'.*r'.*watch.9anime.*.*',
    r'.*r'.*free.9anime.*.*',
    r'.*r'.*stream.9anime.*.*',
    r'.*r'.*online.9anime.*.*',
    r'.*r'.*live.9anime.*.*',
    r'.*r'.*hd.9anime.*.*',
    r'.*r'.*animedao.*.*',
    r'.*r'.*www.animedao.*.*',
    r'.*r'.*watch.animedao.*.*',
    r'.*r'.*free.animedao.*.*',
    r'.*r'.*stream.animedao.*.*',
    r'.*r'.*online.animedao.*.*',
    r'.*r'.*live.animedao.*.*',
    r'.*r'.*hd.animedao.*.*',
    r'.*r'.*animepahe.*.*',
    r'.*r'.*www.animepahe.*.*',
    r'.*r'.*watch.animepahe.*.*',
    r'.*r'.*free.animepahe.*.*',
    r'.*r'.*stream.animepahe.*.*',
    r'.*r'.*online.animepahe.*.*',
    r'.*r'.*live.animepahe.*.*',
    r'.*r'.*hd.animepahe.*.*',
    r'.*r'.*aniwatch.*.*',
    r'.*r'.*www.aniwatch.*.*',
    r'.*r'.*watch.aniwatch.*.*',
    r'.*r'.*free.aniwatch.*.*',
    r'.*r'.*stream.aniwatch.*.*',
    r'.*r'.*online.aniwatch.*.*',
    r'.*r'.*live.aniwatch.*.*',
    r'.*r'.*hd.aniwatch.*.*',
    r'.*r'.*zoro.*.*',
    r'.*r'.*www.zoro.*.*',
    r'.*r'.*watch.zoro.*.*',
    r'.*r'.*free.zoro.*.*',
    r'.*r'.*stream.zoro.*.*',
    r'.*r'.*online.zoro.*.*',
    r'.*r'.*live.zoro.*.*',
    r'.*r'.*hd.zoro.*.*',
    r'.*r'.*animesuge.*.*',
    r'.*r'.*www.animesuge.*.*',
    r'.*r'.*watch.animesuge.*.*',
    r'.*r'.*free.animesuge.*.*',
    r'.*r'.*stream.animesuge.*.*',
    r'.*r'.*online.animesuge.*.*',
    r'.*r'.*live.animesuge.*.*',
    r'.*r'.*hd.animesuge.*.*',
    r'.*r'.*masteranime.*.*',
    r'.*r'.*www.masteranime.*.*',
    r'.*r'.*watch.masteranime.*.*',
    r'.*r'.*free.masteranime.*.*',
    r'.*r'.*stream.masteranime.*.*',
    r'.*r'.*online.masteranime.*.*',
    r'.*r'.*live.masteranime.*.*',
    r'.*r'.*hd.masteranime.*.*',
    r'.*r'.*animekisa.*.*',
    r'.*r'.*www.animekisa.*.*',
    r'.*r'.*watch.animekisa.*.*',
    r'.*r'.*free.animekisa.*.*',
    r'.*r'.*stream.animekisa.*.*',
    r'.*r'.*online.animekisa.*.*',
    r'.*r'.*live.animekisa.*.*',
    r'.*r'.*hd.animekisa.*.*',
    r'.*r'.*torrent.*.*',
    r'.*r'.*www.torrent.*.*',
    r'.*r'.*watch.torrent.*.*',
    r'.*r'.*free.torrent.*.*',
    r'.*r'.*stream.torrent.*.*',
    r'.*r'.*online.torrent.*.*',
    r'.*r'.*live.torrent.*.*',
    r'.*r'.*hd.torrent.*.*',
    r'.*r'.*1337x.*.*',
    r'.*r'.*www.1337x.*.*',
    r'.*r'.*watch.1337x.*.*',
    r'.*r'.*free.1337x.*.*',
    r'.*r'.*stream.1337x.*.*',
    r'.*r'.*online.1337x.*.*',
    r'.*r'.*live.1337x.*.*',
    r'.*r'.*hd.1337x.*.*',
    r'.*r'.*eztv.*.*',
    r'.*r'.*www.eztv.*.*',
    r'.*r'.*watch.eztv.*.*',
    r'.*r'.*free.eztv.*.*',
    r'.*r'.*stream.eztv.*.*',
    r'.*r'.*online.eztv.*.*',
    r'.*r'.*live.eztv.*.*',
    r'.*r'.*hd.eztv.*.*',
    r'.*r'.*limetorrents.*.*',
    r'.*r'.*www.limetorrents.*.*',
    r'.*r'.*watch.limetorrents.*.*',
    r'.*r'.*free.limetorrents.*.*',
    r'.*r'.*stream.limetorrents.*.*',
    r'.*r'.*online.limetorrents.*.*',
    r'.*r'.*live.limetorrents.*.*',
    r'.*r'.*hd.limetorrents.*.*',
    r'.*r'.*torlock.*.*',
    r'.*r'.*www.torlock.*.*',
    r'.*r'.*watch.torlock.*.*',
    r'.*r'.*free.torlock.*.*',
    r'.*r'.*stream.torlock.*.*',
    r'.*r'.*online.torlock.*.*',
    r'.*r'.*live.torlock.*.*',
    r'.*r'.*hd.torlock.*.*',
    r'.*r'.*zooqle.*.*',
    r'.*r'.*www.zooqle.*.*',
    r'.*r'.*watch.zooqle.*.*',
    r'.*r'.*free.zooqle.*.*',
    r'.*r'.*stream.zooqle.*.*',
    r'.*r'.*online.zooqle.*.*',
    r'.*r'.*live.zooqle.*.*',
    r'.*r'.*hd.zooqle.*.*',
    r'.*r'.*kickasstorrents.*.*',
    r'.*r'.*www.kickasstorrents.*.*',
    r'.*r'.*watch.kickasstorrents.*.*',
    r'.*r'.*free.kickasstorrents.*.*',
    r'.*r'.*stream.kickasstorrents.*.*',
    r'.*r'.*online.kickasstorrents.*.*',
    r'.*r'.*live.kickasstorrents.*.*',
    r'.*r'.*hd.kickasstorrents.*.*',
    r'.*r'.*tpb.*.*',
    r'.*r'.*www.tpb.*.*',
    r'.*r'.*watch.tpb.*.*',
    r'.*r'.*free.tpb.*.*',
    r'.*r'.*stream.tpb.*.*',
    r'.*r'.*online.tpb.*.*',
    r'.*r'.*live.tpb.*.*',
    r'.*r'.*hd.tpb.*.*',
    r'.*r'.*movie-stream.*.*',
    r'.*r'.*www.movie-stream.*.*',
    r'.*r'.*watch.movie-stream.*.*',
    r'.*r'.*free.movie-stream.*.*',
    r'.*r'.*stream.movie-stream.*.*',
    r'.*r'.*online.movie-stream.*.*',
    r'.*r'.*live.movie-stream.*.*',
    r'.*r'.*hd.movie-stream.*.*',
    r'.*r'.*movie-streaming.*.*',
    r'.*r'.*www.movie-streaming.*.*',
    r'.*r'.*watch.movie-streaming.*.*',
    r'.*r'.*free.movie-streaming.*.*',
    r'.*r'.*stream.movie-streaming.*.*',
    r'.*r'.*online.movie-streaming.*.*',
    r'.*r'.*live.movie-streaming.*.*',
    r'.*r'.*hd.movie-streaming.*.*',
    r'.*r'.*stream-movie.*.*',
    r'.*r'.*www.stream-movie.*.*',
    r'.*r'.*watch.stream-movie.*.*',
    r'.*r'.*free.stream-movie.*.*',
    r'.*r'.*stream.stream-movie.*.*',
    r'.*r'.*online.stream-movie.*.*',
    r'.*r'.*live.stream-movie.*.*',
    r'.*r'.*hd.stream-movie.*.*',
    r'.*r'.*watch-movie.*.*',
    r'.*r'.*www.watch-movie.*.*',
    r'.*r'.*watch.watch-movie.*.*',
    r'.*r'.*free.watch-movie.*.*',
    r'.*r'.*stream.watch-movie.*.*',
    r'.*r'.*online.watch-movie.*.*',
    r'.*r'.*live.watch-movie.*.*',
    r'.*r'.*hd.watch-movie.*.*',
    r'.*r'.*free-movie.*.*',
    r'.*r'.*www.free-movie.*.*',
    r'.*r'.*watch.free-movie.*.*',
    r'.*r'.*free.free-movie.*.*',
    r'.*r'.*stream.free-movie.*.*',
    r'.*r'.*online.free-movie.*.*',
    r'.*r'.*live.free-movie.*.*',
    r'.*r'.*hd.free-movie.*.*',
    r'.*r'.*free-tv.*.*',
    r'.*r'.*www.free-tv.*.*',
    r'.*r'.*watch.free-tv.*.*',
    r'.*r'.*free.free-tv.*.*',
    r'.*r'.*stream.free-tv.*.*',
    r'.*r'.*online.free-tv.*.*',
    r'.*r'.*live.free-tv.*.*',
    r'.*r'.*hd.free-tv.*.*',
    r'.*r'.*online-tv.*.*',
    r'.*r'.*www.online-tv.*.*',
    r'.*r'.*watch.online-tv.*.*',
    r'.*r'.*free.online-tv.*.*',
    r'.*r'.*stream.online-tv.*.*',
    r'.*r'.*online.online-tv.*.*',
    r'.*r'.*live.online-tv.*.*',
    r'.*r'.*hd.online-tv.*.*',
    r'.*r'.*tv-online.*.*',
    r'.*r'.*www.tv-online.*.*',
    r'.*r'.*watch.tv-online.*.*',
    r'.*r'.*free.tv-online.*.*',
    r'.*r'.*stream.tv-online.*.*',
    r'.*r'.*online.tv-online.*.*',
    r'.*r'.*live.tv-online.*.*',
    r'.*r'.*hd.tv-online.*.*',
    r'.*r'.*series-stream.*.*',
    r'.*r'.*www.series-stream.*.*',
    r'.*r'.*watch.series-stream.*.*',
    r'.*r'.*free.series-stream.*.*',
    r'.*r'.*stream.series-stream.*.*',
    r'.*r'.*online.series-stream.*.*',
    r'.*r'.*live.series-stream.*.*',
    r'.*r'.*hd.series-stream.*.*',
    r'.*r'.*watch-series.*.*',
    r'.*r'.*www.watch-series.*.*',
    r'.*r'.*watch.watch-series.*.*',
    r'.*r'.*free.watch-series.*.*',
    r'.*r'.*stream.watch-series.*.*',
    r'.*r'.*online.watch-series.*.*',
    r'.*r'.*live.watch-series.*.*',
    r'.*r'.*hd.watch-series.*.*',
    r'.*r'.*episode-stream.*.*',
    r'.*r'.*www.episode-stream.*.*',
    r'.*r'.*watch.episode-stream.*.*',
    r'.*r'.*free.episode-stream.*.*',
    r'.*r'.*stream.episode-stream.*.*',
    r'.*r'.*online.episode-stream.*.*',
    r'.*r'.*live.episode-stream.*.*',
    r'.*r'.*hd.episode-stream.*.*',
    r'.*r'.*hd-movie.*.*',
    r'.*r'.*www.hd-movie.*.*',
    r'.*r'.*watch.hd-movie.*.*',
    r'.*r'.*free.hd-movie.*.*',
    r'.*r'.*stream.hd-movie.*.*',
    r'.*r'.*online.hd-movie.*.*',
    r'.*r'.*live.hd-movie.*.*',
    r'.*r'.*hd.hd-movie.*.*',
    r'.*r'.*4k-movie.*.*',
    r'.*r'.*www.4k-movie.*.*',
    r'.*r'.*watch.4k-movie.*.*',
    r'.*r'.*free.4k-movie.*.*',
    r'.*r'.*stream.4k-movie.*.*',
    r'.*r'.*online.4k-movie.*.*',
    r'.*r'.*live.4k-movie.*.*',
    r'.*r'.*hd.4k-movie.*.*',
    r'.*r'.*1080p-movie.*.*',
    r'.*r'.*www.1080p-movie.*.*',
    r'.*r'.*watch.1080p-movie.*.*',
    r'.*r'.*free.1080p-movie.*.*',
    r'.*r'.*stream.1080p-movie.*.*',
    r'.*r'.*online.1080p-movie.*.*',
    r'.*r'.*live.1080p-movie.*.*',
    r'.*r'.*hd.1080p-movie.*.*',
    r'.*r'.*720p-movie.*.*',
    r'.*r'.*www.720p-movie.*.*',
    r'.*r'.*watch.720p-movie.*.*',
    r'.*r'.*free.720p-movie.*.*',
    r'.*r'.*stream.720p-movie.*.*',
    r'.*r'.*online.720p-movie.*.*',
    r'.*r'.*live.720p-movie.*.*',
    r'.*r'.*hd.720p-movie.*.*',
    r'.*r'.*bluray-movie.*.*',
    r'.*r'.*www.bluray-movie.*.*',
    r'.*r'.*watch.bluray-movie.*.*',
    r'.*r'.*free.bluray-movie.*.*',
    r'.*r'.*stream.bluray-movie.*.*',
    r'.*r'.*online.bluray-movie.*.*',
    r'.*r'.*live.bluray-movie.*.*',
    r'.*r'.*hd.bluray-movie.*.*',
    r'.*r'.*dvd-movie.*.*',
    r'.*r'.*www.dvd-movie.*.*',
    r'.*r'.*watch.dvd-movie.*.*',
    r'.*r'.*free.dvd-movie.*.*',
    r'.*r'.*stream.dvd-movie.*.*',
    r'.*r'.*online.dvd-movie.*.*',
    r'.*r'.*live.dvd-movie.*.*',
    r'.*r'.*hd.dvd-movie.*.*',
    r'.*r'.*cam-movie.*.*',
    r'.*r'.*www.cam-movie.*.*',
    r'.*r'.*watch.cam-movie.*.*',
    r'.*r'.*free.cam-movie.*.*',
    r'.*r'.*stream.cam-movie.*.*',
    r'.*r'.*online.cam-movie.*.*',
    r'.*r'.*live.cam-movie.*.*',
    r'.*r'.*hd.cam-movie.*.*',
    r'.*r'.*ts-movie.*.*',
    r'.*r'.*www.ts-movie.*.*',
    r'.*r'.*watch.ts-movie.*.*',
    r'.*r'.*free.ts-movie.*.*',
    r'.*r'.*stream.ts-movie.*.*',
    r'.*r'.*online.ts-movie.*.*',
    r'.*r'.*live.ts-movie.*.*',
    r'.*r'.*hd.ts-movie.*.*',
    r'.*r'.*hdrip-movie.*.*',
    r'.*r'.*www.hdrip-movie.*.*',
    r'.*r'.*watch.hdrip-movie.*.*',
    r'.*r'.*free.hdrip-movie.*.*',
    r'.*r'.*stream.hdrip-movie.*.*',
    r'.*r'.*online.hdrip-movie.*.*',
    r'.*r'.*live.hdrip-movie.*.*',
    r'.*r'.*hd.hdrip-movie.*.*',
    r'.*r'.*webrip-movie.*.*',
    r'.*r'.*www.webrip-movie.*.*',
    r'.*r'.*watch.webrip-movie.*.*',
    r'.*r'.*free.webrip-movie.*.*',
    r'.*r'.*stream.webrip-movie.*.*',
    r'.*r'.*online.webrip-movie.*.*',
    r'.*r'.*live.webrip-movie.*.*',
    r'.*r'.*hd.webrip-movie.*.*',
    r'.*r'.*webdl-movie.*.*',
    r'.*r'.*www.webdl-movie.*.*',
    r'.*r'.*watch.webdl-movie.*.*',
    r'.*r'.*free.webdl-movie.*.*',
    r'.*r'.*stream.webdl-movie.*.*',
    r'.*r'.*online.webdl-movie.*.*',
    r'.*r'.*live.webdl-movie.*.*',
    r'.*r'.*hd.webdl-movie.*.*',
    r'.*r'.*x264-movie.*.*',
    r'.*r'.*www.x264-movie.*.*',
    r'.*r'.*watch.x264-movie.*.*',
    r'.*r'.*free.x264-movie.*.*',
    r'.*r'.*stream.x264-movie.*.*',
    r'.*r'.*online.x264-movie.*.*',
    r'.*r'.*live.x264-movie.*.*',
    r'.*r'.*hd.x264-movie.*.*',
    r'.*r'.*x265-movie.*.*',
    r'.*r'.*www.x265-movie.*.*',
    r'.*r'.*watch.x265-movie.*.*',
    r'.*r'.*free.x265-movie.*.*',
    r'.*r'.*stream.x265-movie.*.*',
    r'.*r'.*online.x265-movie.*.*',
    r'.*r'.*live.x265-movie.*.*',
    r'.*r'.*hd.x265-movie.*.*',
    r'.*r'.*h264-movie.*.*',
    r'.*r'.*www.h264-movie.*.*',
    r'.*r'.*watch.h264-movie.*.*',
    r'.*r'.*free.h264-movie.*.*',
    r'.*r'.*stream.h264-movie.*.*',
    r'.*r'.*online.h264-movie.*.*',
    r'.*r'.*live.h264-movie.*.*',
    r'.*r'.*hd.h264-movie.*.*',
    r'.*r'.*h265-movie.*.*',
    r'.*r'.*www.h265-movie.*.*',
    r'.*r'.*watch.h265-movie.*.*',
    r'.*r'.*free.h265-movie.*.*',
    r'.*r'.*stream.h265-movie.*.*',
    r'.*r'.*online.h265-movie.*.*',
    r'.*r'.*live.h265-movie.*.*',
    r'.*r'.*hd.h265-movie.*.*',
    r'.*r'.*avc-movie.*.*',
    r'.*r'.*www.avc-movie.*.*',
    r'.*r'.*watch.avc-movie.*.*',
    r'.*r'.*free.avc-movie.*.*',
    r'.*r'.*stream.avc-movie.*.*',
    r'.*r'.*online.avc-movie.*.*',
    r'.*r'.*live.avc-movie.*.*',
    r'.*r'.*hd.avc-movie.*.*',
    r'.*r'.*hevc-movie.*.*',
    r'.*r'.*www.hevc-movie.*.*',
    r'.*r'.*watch.hevc-movie.*.*',
    r'.*r'.*free.hevc-movie.*.*',
    r'.*r'.*stream.hevc-movie.*.*',
    r'.*r'.*online.hevc-movie.*.*',
    r'.*r'.*live.hevc-movie.*.*',
    r'.*r'.*hd.hevc-movie.*.*',
    r'.*r'.*paypal-verify.*.*',
    r'.*r'.*www.paypal-verify.*.*',
    r'.*r'.*watch.paypal-verify.*.*',
    r'.*r'.*free.paypal-verify.*.*',
    r'.*r'.*stream.paypal-verify.*.*',
    r'.*r'.*online.paypal-verify.*.*',
    r'.*r'.*live.paypal-verify.*.*',
    r'.*r'.*hd.paypal-verify.*.*',
    r'.*r'.*secure-login.*.*',
    r'.*r'.*www.secure-login.*.*',
    r'.*r'.*watch.secure-login.*.*',
    r'.*r'.*free.secure-login.*.*',
    r'.*r'.*stream.secure-login.*.*',
    r'.*r'.*online.secure-login.*.*',
    r'.*r'.*live.secure-login.*.*',
    r'.*r'.*hd.secure-login.*.*',
    r'.*r'.*account-verify.*.*',
    r'.*r'.*www.account-verify.*.*',
    r'.*r'.*watch.account-verify.*.*',
    r'.*r'.*free.account-verify.*.*',
    r'.*r'.*stream.account-verify.*.*',
    r'.*r'.*online.account-verify.*.*',
    r'.*r'.*live.account-verify.*.*',
    r'.*r'.*hd.account-verify.*.*',
    r'.*r'.*bank-login.*.*',
    r'.*r'.*www.bank-login.*.*',
    r'.*r'.*watch.bank-login.*.*',
    r'.*r'.*free.bank-login.*.*',
    r'.*r'.*stream.bank-login.*.*',
    r'.*r'.*online.bank-login.*.*',
    r'.*r'.*live.bank-login.*.*',
    r'.*r'.*hd.bank-login.*.*',
    r'.*r'.*apple-id.*.*',
    r'.*r'.*www.apple-id.*.*',
    r'.*r'.*watch.apple-id.*.*',
    r'.*r'.*free.apple-id.*.*',
    r'.*r'.*stream.apple-id.*.*',
    r'.*r'.*online.apple-id.*.*',
    r'.*r'.*live.apple-id.*.*',
    r'.*r'.*hd.apple-id.*.*',
    r'.*r'.*icloud-verify.*.*',
    r'.*r'.*www.icloud-verify.*.*',
    r'.*r'.*watch.icloud-verify.*.*',
    r'.*r'.*free.icloud-verify.*.*',
    r'.*r'.*stream.icloud-verify.*.*',
    r'.*r'.*online.icloud-verify.*.*',
    r'.*r'.*live.icloud-verify.*.*',
    r'.*r'.*hd.icloud-verify.*.*',
    r'.*r'.*microsoft-verify.*.*',
    r'.*r'.*www.microsoft-verify.*.*',
    r'.*r'.*watch.microsoft-verify.*.*',
    r'.*r'.*free.microsoft-verify.*.*',
    r'.*r'.*stream.microsoft-verify.*.*',
    r'.*r'.*online.microsoft-verify.*.*',
    r'.*r'.*live.microsoft-verify.*.*',
    r'.*r'.*hd.microsoft-verify.*.*',
    r'.*r'.*amazon-verify.*.*',
    r'.*r'.*www.amazon-verify.*.*',
    r'.*r'.*watch.amazon-verify.*.*',
    r'.*r'.*free.amazon-verify.*.*',
    r'.*r'.*stream.amazon-verify.*.*',
    r'.*r'.*online.amazon-verify.*.*',
    r'.*r'.*live.amazon-verify.*.*',
    r'.*r'.*hd.amazon-verify.*.*',
    r'.*r'.*facebook-login.*.*',
    r'.*r'.*www.facebook-login.*.*',
    r'.*r'.*watch.facebook-login.*.*',
    r'.*r'.*free.facebook-login.*.*',
    r'.*r'.*stream.facebook-login.*.*',
    r'.*r'.*online.facebook-login.*.*',
    r'.*r'.*live.facebook-login.*.*',
    r'.*r'.*hd.facebook-login.*.*',
    r'.*r'.*instagram-login.*.*',
    r'.*r'.*www.instagram-login.*.*',
    r'.*r'.*watch.instagram-login.*.*',
    r'.*r'.*free.instagram-login.*.*',
    r'.*r'.*stream.instagram-login.*.*',
    r'.*r'.*online.instagram-login.*.*',
    r'.*r'.*live.instagram-login.*.*',
    r'.*r'.*hd.instagram-login.*.*',
    r'.*r'.*twitter-login.*.*',
    r'.*r'.*www.twitter-login.*.*',
    r'.*r'.*watch.twitter-login.*.*',
    r'.*r'.*free.twitter-login.*.*',
    r'.*r'.*stream.twitter-login.*.*',
    r'.*r'.*online.twitter-login.*.*',
    r'.*r'.*live.twitter-login.*.*',
    r'.*r'.*hd.twitter-login.*.*',
    r'.*r'.*linkedin-login.*.*',
    r'.*r'.*www.linkedin-login.*.*',
    r'.*r'.*watch.linkedin-login.*.*',
    r'.*r'.*free.linkedin-login.*.*',
    r'.*r'.*stream.linkedin-login.*.*',
    r'.*r'.*online.linkedin-login.*.*',
    r'.*r'.*live.linkedin-login.*.*',
    r'.*r'.*hd.linkedin-login.*.*',
    r'.*r'.*chase-login.*.*',
    r'.*r'.*www.chase-login.*.*',
    r'.*r'.*watch.chase-login.*.*',
    r'.*r'.*free.chase-login.*.*',
    r'.*r'.*stream.chase-login.*.*',
    r'.*r'.*online.chase-login.*.*',
    r'.*r'.*live.chase-login.*.*',
    r'.*r'.*hd.chase-login.*.*',
    r'.*r'.*wellsfargo-login.*.*',
    r'.*r'.*www.wellsfargo-login.*.*',
    r'.*r'.*watch.wellsfargo-login.*.*',
    r'.*r'.*free.wellsfargo-login.*.*',
    r'.*r'.*stream.wellsfargo-login.*.*',
    r'.*r'.*online.wellsfargo-login.*.*',
    r'.*r'.*live.wellsfargo-login.*.*',
    r'.*r'.*hd.wellsfargo-login.*.*',
    r'.*r'.*bankofamerica-login.*.*',
    r'.*r'.*www.bankofamerica-login.*.*',
    r'.*r'.*watch.bankofamerica-login.*.*',
    r'.*r'.*free.bankofamerica-login.*.*',
    r'.*r'.*stream.bankofamerica-login.*.*',
    r'.*r'.*online.bankofamerica-login.*.*',
    r'.*r'.*live.bankofamerica-login.*.*',
    r'.*r'.*hd.bankofamerica-login.*.*',
    r'.*r'.*citibank-login.*.*',
    r'.*r'.*www.citibank-login.*.*',
    r'.*r'.*watch.citibank-login.*.*',
    r'.*r'.*free.citibank-login.*.*',
    r'.*r'.*stream.citibank-login.*.*',
    r'.*r'.*online.citibank-login.*.*',
    r'.*r'.*live.citibank-login.*.*',
    r'.*r'.*hd.citibank-login.*.*',
    r'.*r'.*hsbc-login.*.*',
    r'.*r'.*www.hsbc-login.*.*',
    r'.*r'.*watch.hsbc-login.*.*',
    r'.*r'.*free.hsbc-login.*.*',
    r'.*r'.*stream.hsbc-login.*.*',
    r'.*r'.*online.hsbc-login.*.*',
    r'.*r'.*live.hsbc-login.*.*',
    r'.*r'.*hd.hsbc-login.*.*',
    r'.*r'.*barclays-login.*.*',
    r'.*r'.*www.barclays-login.*.*',
    r'.*r'.*watch.barclays-login.*.*',
    r'.*r'.*free.barclays-login.*.*',
    r'.*r'.*stream.barclays-login.*.*',
    r'.*r'.*online.barclays-login.*.*',
    r'.*r'.*live.barclays-login.*.*',
    r'.*r'.*hd.barclays-login.*.*',
    r'.*r'.*.ph.*.*',
    r'.*r'.*www..ph.*.*',
    r'.*r'.*watch..ph.*.*',
    r'.*r'.*free..ph.*.*',
    r'.*r'.*stream..ph.*.*',
    r'.*r'.*online..ph.*.*',
    r'.*r'.*live..ph.*.*',
    r'.*r'.*hd..ph.*.*',
    r'.*r'.*.to.*.*',
    r'.*r'.*www..to.*.*',
    r'.*r'.*watch..to.*.*',
    r'.*r'.*free..to.*.*',
    r'.*r'.*stream..to.*.*',
    r'.*r'.*online..to.*.*',
    r'.*r'.*live..to.*.*',
    r'.*r'.*hd..to.*.*',
    r'.*r'.*.cc.*.*',
    r'.*r'.*www..cc.*.*',
    r'.*r'.*watch..cc.*.*',
    r'.*r'.*free..cc.*.*',
    r'.*r'.*stream..cc.*.*',
    r'.*r'.*online..cc.*.*',
    r'.*r'.*live..cc.*.*',
    r'.*r'.*hd..cc.*.*',
    r'.*r'.*.run.*.*',
    r'.*r'.*www..run.*.*',
    r'.*r'.*watch..run.*.*',
    r'.*r'.*free..run.*.*',
    r'.*r'.*stream..run.*.*',
    r'.*r'.*online..run.*.*',
    r'.*r'.*live..run.*.*',
    r'.*r'.*hd..run.*.*',
    r'.*r'.*.bz.*.*',
    r'.*r'.*www..bz.*.*',
    r'.*r'.*watch..bz.*.*',
    r'.*r'.*free..bz.*.*',
    r'.*r'.*stream..bz.*.*',
    r'.*r'.*online..bz.*.*',
    r'.*r'.*live..bz.*.*',
    r'.*r'.*hd..bz.*.*',
    r'.*r'.*.ws.*.*',
    r'.*r'.*www..ws.*.*',
    r'.*r'.*watch..ws.*.*',
    r'.*r'.*free..ws.*.*',
    r'.*r'.*stream..ws.*.*',
    r'.*r'.*online..ws.*.*',
    r'.*r'.*live..ws.*.*',
    r'.*r'.*hd..ws.*.*',
    r'.*r'.*.online.*.*',
    r'.*r'.*www..online.*.*',
    r'.*r'.*watch..online.*.*',
    r'.*r'.*free..online.*.*',
    r'.*r'.*stream..online.*.*',
    r'.*r'.*online..online.*.*',
    r'.*r'.*live..online.*.*',
    r'.*r'.*hd..online.*.*',
    r'.*r'.*.site.*.*',
    r'.*r'.*www..site.*.*',
    r'.*r'.*watch..site.*.*',
    r'.*r'.*free..site.*.*',
    r'.*r'.*stream..site.*.*',
    r'.*r'.*online..site.*.*',
    r'.*r'.*live..site.*.*',
    r'.*r'.*hd..site.*.*',
    r'.*r'.*.live.*.*',
    r'.*r'.*www..live.*.*',
    r'.*r'.*watch..live.*.*',
    r'.*r'.*free..live.*.*',
    r'.*r'.*stream..live.*.*',
    r'.*r'.*online..live.*.*',
    r'.*r'.*live..live.*.*',
    r'.*r'.*hd..live.*.*',
    r'.*r'.*.fun.*.*',
    r'.*r'.*www..fun.*.*',
    r'.*r'.*watch..fun.*.*',
    r'.*r'.*free..fun.*.*',
    r'.*r'.*stream..fun.*.*',
    r'.*r'.*online..fun.*.*',
    r'.*r'.*live..fun.*.*',
    r'.*r'.*hd..fun.*.*',
    r'.*r'.*.click.*.*',
    r'.*r'.*www..click.*.*',
    r'.*r'.*watch..click.*.*',
    r'.*r'.*free..click.*.*',
    r'.*r'.*stream..click.*.*',
    r'.*r'.*online..click.*.*',
    r'.*r'.*live..click.*.*',
    r'.*r'.*hd..click.*.*',
    r'.*r'.*.link.*.*',
    r'.*r'.*www..link.*.*',
    r'.*r'.*watch..link.*.*',
    r'.*r'.*free..link.*.*',
    r'.*r'.*stream..link.*.*',
    r'.*r'.*online..link.*.*',
    r'.*r'.*live..link.*.*',
    r'.*r'.*hd..link.*.*',
    r'.*r'.*.press.*.*',
    r'.*r'.*www..press.*.*',
    r'.*r'.*watch..press.*.*',
    r'.*r'.*free..press.*.*',
    r'.*r'.*stream..press.*.*',
    r'.*r'.*online..press.*.*',
    r'.*r'.*live..press.*.*',
    r'.*r'.*hd..press.*.*',
    r'.*r'.*.store.*.*',
    r'.*r'.*www..store.*.*',
    r'.*r'.*watch..store.*.*',
    r'.*r'.*free..store.*.*',
    r'.*r'.*stream..store.*.*',
    r'.*r'.*online..store.*.*',
    r'.*r'.*live..store.*.*',
    r'.*r'.*hd..store.*.*',
    r'.*r'.*.shop.*.*',
    r'.*r'.*www..shop.*.*',
    r'.*r'.*watch..shop.*.*',
    r'.*r'.*free..shop.*.*',
    r'.*r'.*stream..shop.*.*',
    r'.*r'.*online..shop.*.*',
    r'.*r'.*live..shop.*.*',
    r'.*r'.*hd..shop.*.*',
    r'.*r'.*watch.*free.*.*',
    r'.*r'.*stream.*free.*.*',
    r'.*r'.*free.*movies.*.*',
    r'.*r'.*movies.*online.*.*',
    r'.*r'.*free.*tv.*.*',
    r'.*r'.*tv.*series.*free.*.*',
    r'.*r'.*watch.*online.*free.*.*',
    r'.*r'.*download.*movie.*.*',
    r'.*r'.*download.*tv.*.*',
    r'.*r'.*free.*download.*movie.*.*',
    r'.*r'.*stream.*tv.*.*',
    r'.*r'.*watch.*series.*.*',
    r'.*r'.*online.*series.*.*',
    r'.*r'.*free.*streaming.*.*',
    r'.*r'.*hd.*streaming.*.*',
    r'.*r'.*4k.*streaming.*.*',
    r'.*r'.*movie.*download.*.*',
    r'.*r'.*tv.*download.*.*',
    r'.*r'.*episode.*download.*.*',
    r'.*r'.*watch.*full.*movie.*.*',
    r'.*r'.*watch.*full.*episode.*.*',
    r'.*r'.*stream.*full.*movie.*.*',
    r'.*r'.*hd.*movie.*online.*.*',
    r'.*r'.*4k.*movie.*online.*.*',
    r'.*r'.*1080p.*movie.*online.*.*',
    r'.*r'.*verify.*account.*.*',
    r'.*r'.*secure.*login.*.*',
    r'.*r'.*bank.*verify.*.*',
    r'.*r'.*apple.*verify.*.*',
    r'.*r'.*microsoft.*verify.*.*',
    r'.*r'.*amazon.*verify.*.*',
    r'.*r'.*paypal.*verify.*.*',

    r'(mascom|orange|fnb|btc|stanbic|bankofbotswana|bofinet|burs|dhl|choppies).*(promo|free|rewards|cash|prize|verify|login|claim)',
    r'(fnb|stanbic|bank).*(login|secure|verify|blocked|suspended)',
    r'(paypal|amazon|apple|microsoft|google|facebook|instagram|whatsapp|telegram).*(verify|confirm|login|secure|unlock)',
    r'(chase|wellsfargo|bankofamerica|citibank|hsbc|barclays).*(verify|login|secure|unlock)',
    r'(fedex|dhl|ups|usps).*(tracking|delivery|package|customs|fee)',
    r'.*act\s+now.*',
    r'.*immediate\s+action.*',
    r'.*your\s+account\s+(will\s+be|is|has\s+been)\s+(blocked|suspended|frozen|locked)',
    r'.*click\s+here\s+to\s+(verify|confirm|unlock|claim)',
    r'.*you\s+(won|have\s+won|are\s+a\s+winner).*',
    r'.*claim\s+your\s+(prize|reward|cash|money|gift|voucher).*',
    r'.*congratulations.*(won|winner|prize|cash|gift).*',
    r'.*login.*(secure|verify|confirm|update).*',
    r'.*security\s+alert.*',
    r'.*fraud\s+alert.*',
    r'.*unusual\s+activity.*',
    r'.*suspicious\s+activity.*',
    r'.*nigerian\s+prince.*',
    # ─── PIRACY PATTERNS ───
    r'.*123movies.*',
    r'.*fmovies.*',
    r'.*soap2day.*',
    r'.*putlocker.*',
    r'.*gomovies.*',
    r'.*watchseries.*',
    r'.*moviebox.*',
    r'.*thepiratebay.*',
    r'.*yts.*',
    r'.*rarbg.*',
    r'.*popcorntime.*',
    r'.*showbox.*',
    r'.*cinemahd.*',
]

# ============================================================
# LAYER 2: PLATFORM WILDCARDS — WORLDWIDE
# ============================================================
PLATFORM_WILDCARDS = {
    "github.io", "vercel.app", "netlify.app", "pages.dev",
    "gitlab.io", "herokuapp.com", "azurewebsites.net", "cloudfront.net",
    "s3.amazonaws.com", "wordpress.com", "blogger.com", "medium.com",
    "substack.com", "hashnode.dev", "dev.to", "notion.site",
    "glitch.com", "replit.app", "codesandbox.io", "stackblitz.com",
    "codepen.io", "jsfiddle.net", "observablehq.com",
    "colab.research.google.com", "kaggle.com", "huggingface.co",
    "replicate.com", "gradio.app", "streamlit.app", "render.com",
    "fly.io", "railway.app", "cyclic.sh", "deno.dev",
    "cloudflare.dev", "workers.dev", "raw.githubusercontent.com",
    "blob.core.windows.net", "storage.googleapis.com",
    "firebasestorage.googleapis.com",
    "github.dev", "gitpod.io", "codespaces.com",
    "pythonanywhere.com", "replit.com",
    "glitch.me", "surge.sh", "neocities.org",
    "netlify.com", "vercel.com", "cloudflare.com",
    "page.dev", "workers.dev", "popsy.co",
    "webflow.io", "editorx.io", "duda.co",
    "wixsite.com", "godaddysites.com", "weebly.com",
}

# ============================================================
# LAYER 3: STRICT INSTITUTIONAL TLDs — WORLDWIDE
# ============================================================
STRICT_TLDS = {
    ".gov", ".gov.bw", ".gov.za", ".gov.uk", ".gov.au", ".gov.ca",
    ".gov.in", ".gov.ng", ".gov.ke", ".gov.gh", ".gov.eg",
    ".edu", ".edu.bw", ".edu.za", ".edu.au", ".edu.ca",
    ".edu.in", ".edu.ng", ".edu.ke", ".edu.gh", ".edu.eg",
    ".ac.bw", ".ac.za", ".ac.uk", ".ac.in", ".ac.ke",
    ".mil", ".mil.za", ".mil.uk", ".mil.au", ".mil.ca",
}

# ============================================================
# URL NORMALIZATION — Fix trailing slash issues
# ============================================================
def normalize_url(url):
    """Remove trailing slash for consistent detection"""
    if url and url.endswith('/'):
        url = url[:-1]
    return url

# ============================================================
# MAIN WHITELIST CHECKER
# ============================================================

def is_trusted_domain(domain):
    if domain in BLACKLISTED_DOMAINS:
        return False
    domain = domain.lower().strip()
    
    if domain.startswith('http://') or domain.startswith('https://'):
        parsed = urlparse(domain)
        domain = parsed.netloc or domain
    if '/' in domain:
        domain = domain.split('/')[0]
    if ':' in domain:
        domain = domain.split(':')[0]
    if domain.startswith('www.'):
        domain = domain[4:]
    
    
    # EXCEPTION: Whitelist your own backend
    if domain.endswith('.vercel.app'):
        return True
    
    # LAYER 1: Exact Match
    if domain in TRUSTED_DOMAINS:
        return True
    
    # LAYER 1.5: Botswana Brand Protection
    for brand, data in BOTSWANA_BRANDS.items():
        if brand in domain:
            if any(domain == trusted or domain.endswith('.' + trusted) for trusted in data["trusted"]):
                return True
            if any(sus in domain for sus in data["suspicious"]):
                return False
    
    # LAYER 1.5: Phishing Patterns
    if any(re.search(pattern, domain, re.IGNORECASE) for pattern in SUSPICIOUS_PATTERNS):
        return False
    
    if any(domain.endswith(tld) for tld in SUSPICIOUS_TLDS):
        return False
    
    # LAYER 2: Platform Wildcards
    if any(domain == wc or domain.endswith('.' + wc) for wc in PLATFORM_WILDCARDS):
        return True
    
    # LAYER 3: Strict TLDs
    if any(domain.endswith(tld) for tld in STRICT_TLDS):
        return True
    
    # LAYER 4: ML Engine
    return False

# ============================================================
# URL SERVICE CLASS
# ============================================================

class URLService:
    def __init__(self):
        self.model = URLModel()
        
        feature_paths = [
            '/home/cheezboi/models/url_features.json',
            'models/url_features.json',
            '../models/url_features.json',
            os.path.join(os.path.dirname(__file__), '../models/url_features.json'),
            os.path.join(os.getcwd(), 'models/url_features.json')
        ]
        
        features_loaded = False
        for path in feature_paths:
            try:
                if os.path.exists(path):
                    with open(path, 'r') as f:
                        self.features = json.load(f)
                    print(f"   URL features loaded from: {path}")
                    features_loaded = True
                    break
            except:
                continue
        
        if not features_loaded:
            print("   WARNING: url_features.json not found, using default features")
            self.features = [
                'url_len', 'dot_cnt', 'slash_cnt', 'dash_cnt', 
                'under_cnt', 'digit_cnt', 'special_cnt', 'is_https',
                'eq_cnt', 'qm_cnt', 'amp_cnt', 'letter_cnt',
                'dom_len', 'subdom_cnt', 'tld_len', 'is_ip',
                'letter_ratio', 'digit_ratio', 'spec_ratio',
                'path_len', 'query_len', 'entropy'
            ]
        
        print(f"   URL features loaded: {len(self.features)} features")
        print(f"   L1 Trusted Domains: {len(TRUSTED_DOMAINS)}")
        print(f"   L1.5 Botswana Brands: {len(BOTSWANA_BRANDS)}")
        print(f"   L2 Platform Wildcards: {len(PLATFORM_WILDCARDS)}")
        print(f"   L3 Strict TLDs: {len(STRICT_TLDS)}")
        print(f"   L4 ML Engine: Active")
    
    def _is_whitelisted(self, url):
        try:
            # Normalize URL (remove trailing slash)
            url = normalize_url(url)
            parsed = urlparse(url)
            domain = parsed.netloc.lower()
            if domain.startswith("www."):
                domain = domain[4:]
            if ":" in domain:
                domain = domain.split(":")[0]
            return is_trusted_domain(domain)
        except Exception:
            return False
    
    def extract_features(self, url):
        url = str(url).lower()
        features = {}
        
        features['url_len'] = len(url)
        features['dot_cnt'] = url.count('.')
        features['slash_cnt'] = url.count('/')
        features['dash_cnt'] = url.count('-')
        features['under_cnt'] = url.count('_')
        features['digit_cnt'] = sum(c.isdigit() for c in url)
        features['special_cnt'] = len(re.findall(r'[^a-zA-Z0-9]', url))
        features['is_https'] = 1 if 'https' in url else 0
        features['eq_cnt'] = url.count('=')
        features['qm_cnt'] = url.count('?')
        features['amp_cnt'] = url.count('&')
        features['letter_cnt'] = sum(c.isalpha() for c in url)
        
        try:
            parsed = urlparse(url)
            domain = parsed.netloc or parsed.path
            parts = domain.split('.')
            features['dom_len'] = len(parts[-1]) if parts else 0
            features['subdom_cnt'] = max(0, len(parts) - 2)
            features['tld_len'] = len(parts[-1]) if len(parts) > 1 else 0
            features['is_ip'] = 1 if parts and re.match(r'^\d+\.\d+\.\d+\.\d+$', parts[0]) else 0
        except:
            features['dom_len'] = 0
            features['subdom_cnt'] = 0
            features['tld_len'] = 0
            features['is_ip'] = 0
        
        total_chars = len(url) if len(url) > 0 else 1
        features['letter_ratio'] = features['letter_cnt'] / total_chars
        features['digit_ratio'] = features['digit_cnt'] / total_chars
        features['spec_ratio'] = features['special_cnt'] / total_chars
        
        try:
            parsed = urlparse(url)
            features['path_len'] = len(parsed.path)
            features['query_len'] = len(parsed.query)
        except:
            features['path_len'] = 0
            features['query_len'] = 0
        
        if len(url) > 0:
            freq = Counter(url)
            entropy = -sum((count/len(url)) * math.log2(count/len(url)) for count in freq.values())
            features['entropy'] = entropy
        else:
            features['entropy'] = 0
        
        features_df = pd.DataFrame([features])
        for col in self.features:
            if col not in features_df.columns:
                features_df[col] = 0
        features_df = features_df[self.features]
        
        return features_df
    
    def detect(self, url):
        try:
            # Normalize URL (remove trailing slash)
            url = normalize_url(url)
            
            # LAYER 1-3: Whitelist Check
            if self._is_whitelisted(url):
                return {
                    'is_phishing': False,
                    'probability': 0.0,
                    'result': 'legitimate',
                    'reason': 'Verified Trusted Domain'
                }
            
            # LAYER 4: ML Engine for ALL other domains
            features = self.extract_features(url)
            scaled = self.model.scale(features)
            
            pred = self.model.predict(scaled)[0]
            prob = self.model.predict_proba(scaled)[0]
            
            result = self.model.decode(pred)
            confidence = float(max(prob))
            
            return {
                'is_phishing': bool(result == 1),
                'probability': confidence,
                'result': 'phishing' if result == 1 else 'legitimate',
                'reason': 'ML Analysis'
            }
            
        except Exception as e:
            print(f"Error in detect: {str(e)}")
            print(traceback.format_exc())
            return {
                'is_phishing': False,
                'probability': 0.0,
                'result': 'error',
                'error': str(e)
            }

# FORCE DEPLOY - posix.times_result(user=0.02, system=0.0, children_user=0.0, children_system=0.0, elapsed=4333695.37)
